package-lock.json, package.json, src/App.tsx
Add ant dependency and config the theme
=> Ant design

package-lock.json, package.json, src/App.tsx, src/core/store.ts, src/index.css, src/main.tsx, src/pages/layouts/BaseLayout.tsx, src/pages/layouts/BaseLayoutStyles.ts
This feature adds innit configuration for Redux toolkit
Added Dependencies "react-redux" and "@reduxjs/toolkit", create file Store.ts and Added Provider component of "react redux" on main.tsx file
I watched the video of redux and now I know that redux is like a database on client side
[[WMA-15](https://cdentalcaregroup.atlassian.net/browse/WMA-15)
[WMA-15]: https://cdentalcaregroup.atlassian.net/browse/WMA-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 15/redux toolkit

package-lock.json, package.json, src/App.tsx, src/main.tsx, src/pages/layouts/BaseLayout.tsx, src/pages/proofPages/proofPages.tsx, src/pages/routes/Routes.tsx, src/pages/routes/models/Route.tsx
Adds react-router-dom dependency
reac-router-dom dependency added and BrowserRoutes, Routes and Route component added on main.tsx file
Any note
[WMA-18] (https://cdentalcaregroup.atlassian.net/browse/WMA-18)
[WMA-18]: https://cdentalcaregroup.atlassian.net/browse/WMA-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> react-router-dom

package-lock.json, package.json, src/App.tsx, src/components/CustomButtons.tsx, src/components/PaginatedList.tsx, src/data/company/company.ts, src/pages/auth/Login.tsx, src/pages/company/Companies.tsx, src/pages/company/components/CompaniesTable.tsx, src/pages/company/components/CompanyCard.tsx, src/pages/company/components/CompanyTable.tsx, src/pages/company/components/tableHeight.ts, src/pages/layouts/BaseLayout.tsx, src/pages/layouts/BaseLayoutStyles.ts, src/pages/proofPages/proofPages.tsx, src/pages/routes/Routes.tsx, src/services/companyService.ts, src/utils/Constants.ts, src/utils/Extensions.ts, src/utils/Strings.ts, src/utils/strings.ts
This feature presents companies data
Components created: CompaniesTable, CompanyCard, PaginatedList.
Service created: CompanyService with getCompanies mutation
Add use-debounce dependency to manage the table resize. this is calculated in the tableHeight.ts file.
Check it out the design, the card design and the table design are not the best so we can change it in the future of course
Important! The Strings file i dont know why is not working well I hope when I push to the repository it fix it
[WMA-28](https://cdentalcaregroup.atlassian.net/browse/WMA-28)
[WMA-28]: https://cdentalcaregroup.atlassian.net/browse/WMA-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Get Companies responsive

src/utils/strings.ts
Describe the feature / bug. If it's a bug, explain the root cause and how to reproduce.
Describe your changes and explain the technical solution.
Add some notes
[TICKET](https://cdentalcaregroup.atlassian.net/browse/)
Provide screenshots or screencasts demoing your changes. 200px width is a good default for most screenshots.
e.g. <img width="200" alt="screenshot" src="...">
=> release 1.0.1

src/pages/routes/Routes.tsx, src/utils/Strings.ts
Describe the feature / bug. If it's a bug, explain the root cause and how to reproduce.
Describe your changes and explain the technical solution.
Add some notes
[TICKET](https://cdentalcaregroup.atlassian.net/browse/)
Provide screenshots or screencasts demoing your changes. 200px width is a good default for most screenshots.
e.g. <img width="200" alt="screenshot" src="...">
=> fix labels

src/core/genericReducer.ts, src/core/store.ts, src/data/company/company.request.ts, src/pages/company/Companies.tsx, src/pages/company/components/CompanyCard.tsx, src/pages/company/components/CompanyTable.tsx, src/pages/company/components/UpdateCompany.tsx, src/pages/company/components/UpdateCompanyForm.tsx, src/services/companyService.ts, src/utils/localizations/Strings.ts
In this feature now you can update companies
Files Added: UpdateCompany.tsx, UpdateCompanyForm.tsx and Generic reducer to store data when we want update some from another component.
any notes
[WMA-27](https://cdentalcaregroup.atlassian.net/browse/WMA-27)
Good rquests
When we save a duplicated rfc
[WMA-27]: https://cdentalcaregroup.atlassian.net/browse/WMA-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Update Form and modal

src/pages/company/Companies.tsx, src/pages/company/components/CompanyTable.tsx, src/utils/localizations/Strings.ts
This refactor removes a button
Remove 'clear filters and sorters' button in Companies.tsx and add a string for No extension
...
[WMA-46](https://cdentalcaregroup.atlassian.net/browse/WMA-46)
no images needed
[WMA-46]: https://cdentalcaregroup.atlassian.net/browse/WMA-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove 'clear filters and sorters' button in Companies.tsx

src/App.tsx, src/components/ModalForm.tsx, src/pages/company/Companies.tsx, src/pages/company/components/UpdateCompany.tsx, src/pages/company/components/UpdateCompanyForm.tsx
This refactor fixes the update company form bugs 
The ModalForm component now receive one more prop called "isUpdateForm" when is set to true the fields when you close the modal wont be clear.
The close modal cross at the top, now is visible with black color.
[WMA-64](https://cdentalcaregroup.atlassian.net/browse/WMA-64)
[WMA-64]: https://cdentalcaregroup.atlassian.net/browse/WMA-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Modal component updated, Update company components updated

src/pages/layouts/BaseLayout.tsx, src/utils/localizations/Strings.ts
This feature adds tag version
Add span tag at the right bottom of the screen
[WMA-44](https://cdentalcaregroup.atlassian.net/browse/WMA-44)
[WMA-44]: https://cdentalcaregroup.atlassian.net/browse/WMA-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add tag version

src/data/cardtypes/cardTypes.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/company/components/CompanyTable.tsx, src/pages/priority/Priorities.tsx, src/pages/priority/components/PriorityTable.tsx, src/pages/routes/Routes.tsx, src/pages/site/components/SiteTable.tsx, src/pages/site/components/ViewCardTypesButton.tsx, src/services/CardTypesService.ts, src/utils/Extensions.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
Now you can view in a table the card types
...See the notes
There are changes in the buttons of all tables, for now they are aligned to the right
[WMA-36](https://cdentalcaregroup.atlassian.net/browse/WMA-36)
[WMA-36]: https://cdentalcaregroup.atlassian.net/browse/WMA-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Now you can view in a table the card types

src/data/preclassifier/preclassifier.ts, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/ViewPreclassifiersButton.tsx, src/pages/preclassifier/Preclassifiers.tsx, src/pages/preclassifier/components/PreclassifierCard.tsx, src/pages/preclassifier/components/PreclassifierTable.tsx, src/pages/routes/Routes.tsx, src/services/preclassifierService.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
Get preclassifiers
Add table and card components
....
[WMA-52](https://cdentalcaregroup.atlassian.net/browse/WMA-52)
[WMA-52]: https://cdentalcaregroup.atlassian.net/browse/WMA-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 52/get preclassifiers

src/data/cardtypes/cardTypes.request.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/RegisterCardTypeForm.tsx, src/services/CardTypesService.ts, src/utils/localizations/Strings.ts
Create card type
RegisterService.ts and RegiterForm.tsx  added, ModalForm implemented
For now, the responsible select is static in the front end
[WMA-37](https://cdentalcaregroup.atlassian.net/browse/WMA-37)
[WMA-37]: https://cdentalcaregroup.atlassian.net/browse/WMA-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create card type

src/App.tsx, src/pages/auth/Logout.tsx, src/pages/layouts/BaseLayout.tsx, src/utils/localizations/Strings.ts
Now you can Log out
Create a component to log out, clear the session storage and the auth reducer.
Modal confirms implemented
Add some notes
[WMA-61](https://cdentalcaregroup.atlassian.net/browse/WMA-61)
[WMA-61]: https://cdentalcaregroup.atlassian.net/browse/WMA-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Log out now is possible

src/config/firebase.ts, src/config/firebaseUpload.ts, src/pages/company/Companies.tsx, src/pages/company/components/RegisterCompanyForm.tsx, src/pages/site/Sites.tsx, src/pages/site/components/RegisterSiteForm.tsx, src/utils/localizations/Strings.ts
Now you can upload your own images
Firebase config and funticion to upload image and then get the url 
[WMA-54](https://cdentalcaregroup.atlassian.net/browse/WMA-54)
[WMA-54]: https://cdentalcaregroup.atlassian.net/browse/WMA-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> now the you can upload your own images

src/core/genericReducer.ts, src/data/cardtypes/cardTypes.request.ts, src/data/cardtypes/cardTypes.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/services/CardTypesService.ts
Update Card type now is possible
Adds: update form, update service, getone service, and update card type component
...
[WMA-38](https://cdentalcaregroup.atlassian.net/browse/WMA-38)
[WMA-38]: https://cdentalcaregroup.atlassian.net/browse/WMA-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Card type

src/components/PageTitle.tsx, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/ViewPreclassifiersButton.tsx, src/pages/company/Companies.tsx, src/pages/preclassifier/Preclassifiers.tsx, src/pages/priority/Priorities.tsx, src/pages/site/Sites.tsx, src/utils/localizations/Strings.ts
update pages title
Create a title component to centralize design
remove placeholder from search inputs
[WMA-68](https://cdentalcaregroup.atlassian.net/browse/WMA-68)
[WMA-68]: https://cdentalcaregroup.atlassian.net/browse/WMA-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update pages title

src/data/level/level.ts, src/pages/level/Levels.tsx, src/pages/level/components/LevelCollapse.tsx, src/pages/routes/Routes.tsx, src/pages/site/components/SiteCard.tsx, src/pages/site/components/SiteTable.tsx, src/pages/site/components/ViewLevelsButton.tsx, src/services/levelService.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
get site levels
get site levels
get site levels
[WMA-85](https://cdentalcaregroup.atlassian.net/browse/WMA-85)
[WMA-85]: https://cdentalcaregroup.atlassian.net/browse/WMA-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> get site levels

src/data/user/user.ts, src/pages/routes/Routes.tsx, src/pages/user/Users.tsx, src/pages/user/components/UserTable.tsx, src/services/userService.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
get users in a table
get users in a table
get users in a table
[WMA-84](https://cdentalcaregroup.atlassian.net/browse/WMA-84)
[WMA-84]: https://cdentalcaregroup.atlassian.net/browse/WMA-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> get users in a table

src/core/genericReducer.ts, src/data/cardtypes/cardTypes.request.ts, src/data/cardtypes/cardTypes.ts, src/data/user/user.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/RegisterCardTypeForm.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/services/userService.ts, src/utils/localizations/Strings.ts
Update forms for the new updates in the database
Update forms for the new updates in the database
Update forms for the new updates in the database
[WMA-110](https://cdentalcaregroup.atlassian.net/browse/WMA-110)
[WMA-110]: https://cdentalcaregroup.atlassian.net/browse/WMA-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update forms for the new updates in the database

src/components/ModalForm.tsx, src/core/genericReducer.ts, src/data/level/level.request.ts, src/pages/level/Levels.tsx, src/pages/level/components/LevelCollapse.tsx, src/pages/level/components/RegisterLevelForm.tsx, src/pages/level/components/RegisterNodeButton.tsx, src/services/levelService.ts, src/utils/localizations/Strings.ts
create leves and its nodes
create leves and its nodes
create leves and its nodes
[WMA-75](https://cdentalcaregroup.atlassian.net/browse/WMA-75)
create level
create node (level inside a levels)
[WMA-75]: https://cdentalcaregroup.atlassian.net/browse/WMA-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> create leves and its nodes

src/data/user/user.request.ts, src/pages/user/Users.tsx, src/pages/user/components/RegisterUserForm.tsx, src/services/roleService.ts, src/services/userService.ts, src/utils/Extensions.ts, src/utils/localizations/Strings.ts
Create user first view
In this feature we implemented the create user form 
For now the sites are harcoded cause that Lic. Fausto said in whatsapp maybe we need to change the users to the sites options
[WMA-81](https://cdentalcaregroup.atlassian.net/browse/WMA-81)
[WMA-81]: https://cdentalcaregroup.atlassian.net/browse/WMA-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create user first view

src/data/cardtypes/cardTypes.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/RegisterCardTypeForm.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/services/CardTypesService.ts, src/utils/localizations/Strings.ts
changes in card type forms
changes in card type forms
changes in card type forms
[WMA-119](https://cdentalcaregroup.atlassian.net/browse/WMA-119)
[WMA-119]: https://cdentalcaregroup.atlassian.net/browse/WMA-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> changes in card type forms

src/core/genericReducer.ts, src/data/currency/currency.ts, src/data/site/site.request.ts, src/data/site/site.ts, src/pages/site/Sites.tsx, src/pages/site/components/RegisterSiteForm.tsx, src/pages/site/components/UpdateSiteForm.tsx, src/services/currencyService.ts, src/utils/Extensions.ts, src/utils/localizations/Strings.ts
Feature/wma 112/add radio button for users types when create a new site
Feature/wma 112/add radio button for users types when create a new site
Feature/wma 112/add radio button for users types when create a new site
[WMA-112](https://cdentalcaregroup.atlassian.net/browse/WMA-112)
[WMA-112]: https://cdentalcaregroup.atlassian.net/browse/WMA-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 112/add radio button for users types when create a new site

src/App.tsx, src/data/site/site.ts, src/pages/site/Sites.tsx, src/pages/user/components/RegisterUserForm.tsx, src/services/siteService.ts
Update the create users form
Update the create users form now we get the all the sites, and we can see the user license, current users and user quantity
Also changes in the theme, I removed the color icons.
[WMA-118](https://cdentalcaregroup.atlassian.net/browse/WMA-118)
[WMA-118]: https://cdentalcaregroup.atlassian.net/browse/WMA-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the create users form

src/core/genericReducer.ts, src/data/user/user.request.ts, src/data/user/user.ts, src/pages/user/Users.tsx, src/pages/user/components/UpdateUserButton.tsx, src/pages/user/components/UpdateUserForm.tsx, src/pages/user/components/UserTable.tsx, src/services/userService.ts, src/utils/localizations/Strings.ts
Update user form implemented
Update user form implemented
[WMA-83](https://cdentalcaregroup.atlassian.net/browse/WMA-83)
[WMA-83]: https://cdentalcaregroup.atlassian.net/browse/WMA-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update user form implemented

src/App.tsx, src/data/user/user.request.ts, src/pages/auth/Login.tsx, src/pages/auth/ResetPassword.tsx, src/services/userService.ts, src/utils/Notifications.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
Forgot password process
Create another page called ResetPassword and its route.
Service to call the endpoint implemented in userService
SendCode and ResetPasswordClass were created
Add some notes
**[WMA-131](https://cdentalcaregroup.atlassian.net/browse/WMA-131)**
orderly process
[WMA-131]: https://cdentalcaregroup.atlassian.net/browse/WMA-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> forgot password process

src/pages/card/components/Card.tsx, src/utils/localizations/Strings.ts
refactor preclassifier to proble type in cards section
refactor preclassifier to proble type in cards section
refactor preclassifier to proble type in cards section
[WMA-132](https://cdentalcaregroup.atlassian.net/browse/WMA-132)
[WMA-132]: https://cdentalcaregroup.atlassian.net/browse/WMA-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor preclassifier to proble type in cards section

src/data/status/status.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/services/CardTypesService.ts, src/services/statusService.ts, src/utils/localizations/Strings.ts
field to change the status added
Was created the status service to get the database status
The useGetAllCardTypes was updated since it was created another endpoint
The modal name was updated to 'Update card type'
Also the button delete was removed
[WMA-143](https://cdentalcaregroup.atlassian.net/browse/WMA-143)
[WMA-143]: https://cdentalcaregroup.atlassian.net/browse/WMA-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> filed to change the status added

src/data/status/status.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/pages/preclassifier/Preclassifiers.tsx, src/pages/preclassifier/components/PreclassifierCard.tsx, src/pages/preclassifier/components/PreclassifierTable.tsx, src/pages/preclassifier/components/UpdatePreclassifierForm.tsx, src/services/CardTypesService.ts, src/services/preclassifierService.ts, src/services/statusService.ts, src/utils/localizations/Strings.ts
Feature / Bug Description
status added to the update options
Solution
The same as the other pull request, was implemented a status field in the update form
Notes
I made the pull request into the Delete card type because I created the status service there.
Then I will make a merge of each delete ticket into it to finally merge the Delete card type branch in develop
Tickets
[WMA-144](https://cdentalcaregroup.atlassian.net/browse/WMA-144)
Screenshots / Screencasts
[WMA-144]: https://cdentalcaregroup.atlassian.net/browse/WMA-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 144/delete preclassifier

src/data/status/status.ts, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/CardTypesCard.tsx, src/pages/cardtypes/components/CardTypesTable.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/cardtypes/components/UpdateCardTypeForm.tsx, src/pages/priority/Priorities.tsx, src/pages/priority/components/PriorityCard.tsx, src/pages/priority/components/PriorityTable.tsx, src/pages/priority/components/UpdatePriority.tsx, src/pages/priority/components/UpdatePriorityForm.tsx, src/services/CardTypesService.ts, src/services/priorityService.ts, src/services/statusService.ts, src/utils/localizations/Strings.ts
Logical delete
Was created the status service to get the database status
The useGetAllPriorities was updated since it was created another endpoint
Notes
The modal name was updated to 'Update priority'
The delete button was removed
Gap-2 added in the page title
Was added cards view for smallest screens
[WMA-145](https://cdentalcaregroup.atlassian.net/browse/WMA-145)
[WMA-145]: https://cdentalcaregroup.atlassian.net/browse/WMA-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 145/delete priority

src/pages/level/components/LevelCollapse.tsx, src/pages/level/components/RegisterLevelForm.tsx, src/pages/level/components/UpdateLevelForm.tsx, src/services/levelService.ts, src/utils/Extensions.ts, src/utils/localizations/Strings.ts
Change status in levels
Update get all levels enpoind in the service
Status indicator added in levels
[WMA-146](https://cdentalcaregroup.atlassian.net/browse/WMA-146)
[WMA-146]: https://cdentalcaregroup.atlassian.net/browse/WMA-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/wma 146/delete levels

src/pages/routes/Routes.tsx, src/pages/site/components/SiteCard.tsx, src/pages/site/components/SiteTable.tsx, src/pages/site/components/ViewUsersButton.tsx, src/pages/user/SiteUsers.tsx, src/pages/user/components/RegisterSiteUserForm.tsx, src/pages/user/components/RegisterUserForm.tsx, src/pages/user/components/UpdateSiteUserForm.tsx, src/pages/user/components/UpdateUserButton.tsx, src/pages/user/components/UserTable.tsx, src/services/userService.ts, src/utils/Routes.ts, src/utils/localizations/Strings.ts
manage users moved
Add new components to get all users by site
This adds another action in the sites table and also keep the last managment just in case that we want to use it
[WMA-127](https://cdentalcaregroup.atlassian.net/browse/WMA-127)
[WMA-127]: https://cdentalcaregroup.atlassian.net/browse/WMA-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> manage users moved

src/components/EvidenceIndicator.tsx, src/data/card/card.ts, src/data/charts/charts.ts, src/pages/card/components/Card.tsx, src/pages/carddetails/CardDetails.tsx, src/pages/carddetails/components/DefinitiveSolutionCollapse.tsx, src/pages/carddetails/components/EvidenceCollapse.tsx, src/pages/carddetails/components/InfoCollapse.tsx, src/pages/carddetails/components/NoteCollapse.tsx, src/pages/carddetails/components/ProvisionalSolutionCollapse.tsx, src/pages/charts/Charts.tsx, src/pages/charts/components/AreasChart.tsx, src/pages/charts/components/MachinesChart.tsx, src/pages/charts/components/MethodologiesChart.tsx, src/pages/charts/components/PreclassifiersChart.tsx, src/pages/charts/components/WeeksChart.tsx, src/services/chartService.ts, src/utils/Extensions.ts, src/utils/localizations/Strings.ts
Charts and card details
Charts and card details
changes requested
Chart & Reports request changes
Provide screenshots or screencasts demoing your changes. 200px width is a good default for most screenshots.
e.g. <img width="200" alt="screenshot" src="...">
=> Charts and card details

index.html, src/data/level/level.request.ts, src/data/level/level.ts, src/pages/level/Levels.tsx, src/pages/level/components/LevelCollapse.tsx, src/pages/level/components/RegisterLevelForm.tsx, src/pages/level/components/RegisterNodeButton.tsx, src/pages/level/components/UpdateLevelButton.tsx, src/pages/level/components/UpdateLevelForm.tsx, src/utils/localizations/Strings.ts
Feature / Bug Description
changes in levels
Solution
changes in levels
Notes
changes in levels
Tickets
[WMA-159](https://cdentalcaregroup.atlassian.net/browse/WMA-159)
[WMA-159]: https://cdentalcaregroup.atlassian.net/browse/WMA-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> changes in levels

src/data/card/card.request.ts, src/pages/carddetails/components/InfoCollapse.tsx, src/pages/carddetails/components/UpdateMechanicForm.tsx, src/services/cardService.ts, src/services/userService.ts, src/utils/localizations/Strings.ts
refactor mechanic instead of responsible
refactor mechanic instead of responsible
[WMA-160](https://cdentalcaregroup.atlassian.net/browse/WMA-160)
no image needed
[WMA-160]: https://cdentalcaregroup.atlassian.net/browse/WMA-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor mechanic instead of responsible

src/components/CustomDrawerCardList.tsx, src/components/CustomLegend.tsx, src/components/CustomToolTip.tsx, src/components/PaginatedList.tsx, src/data/charts/charts.ts, src/pages/carddetails/components/InfoCollapse.tsx, src/pages/cardtypes/CardTypes.tsx, src/pages/cardtypes/components/RegisterCardTypeForm.tsx, src/pages/cardtypes/components/UpdateCardType.tsx, src/pages/charts/Charts.tsx, src/pages/charts/components/AreasChart.tsx, src/pages/charts/components/CreatorsChart.tsx, src/pages/charts/components/DefinitiveUsersChart.tsx, src/pages/charts/components/MachinesChart.tsx, src/pages/charts/components/MechanicsChart.tsx, src/pages/charts/components/PreclassifiersChart.tsx, src/pages/routes/Routes.tsx, src/services/cardService.ts, src/services/chartService.ts, src/utils/Extensions.ts, src/utils/localizations/Strings.ts
Stacked charts now are available
Modify the structure of charts and a Drawer was added to list the bar chart cards
[[TICKET](https://cdentalcaregroup.atlassian.net/browse/)](https://cdentalcaregroup.atlassian.net/browse/WMA-163)
no image needed
=> Feature/wma 163/chart & reports request changes v2

src/pages/user/components/UserTable.tsx
Bugs in users.tsx component
SiteId now is optional in UserTable Component since there was a problem
[[TICKET](https://cdentalcaregroup.atlassian.net/browse/)](https://cdentalcaregroup.atlassian.net/browse/WMA-167)
=> Bugs in users

src/pages/charts/Charts.tsx, src/pages/charts/components/AreasChart.tsx, src/pages/charts/components/CreatorsChart.tsx, src/pages/charts/components/DefinitiveUsersChart.tsx, src/pages/charts/components/DownloadCardDataExcelButton.tsx, src/pages/charts/components/MachinesChart.tsx, src/pages/charts/components/MechanicsChart.tsx, src/pages/charts/components/PreclassifiersChart.tsx, src/services/chartService.ts, src/services/exportService.ts, src/utils/localizations/Strings.ts
Describe the feature / bug. If it's a bug, explain the root cause and how to reproduce.
Describe your changes and explain the technical solution.
Add some notes
[TICKET](https://cdentalcaregroup.atlassian.net/browse/)
Provide screenshots or screencasts demoing your changes. 200px width is a good default for most screenshots.
e.g. <img width="200" alt="screenshot" src="...">
=> Now you can filter reports and download cards data (#83)
